import polars as pl
from dataclasses import dataclass

TARGET_COL = "TARGET"
ID_COL = "SK_ID_CURR"

# ── Dummy columns generated by to_dummies() in build_features.py ──────────────
PREV_CONTRACT_STATUSES = ["Approved", "Refused", "Canceled", "Unused offer"]
PREV_DUMMY_FEATURES = [f"prev_most_recent_status_{s}" for s in PREV_CONTRACT_STATUSES]

# ── Feature group lists ────────────────────────────────────────────────────────
BUREAU_FEATURES = [
    "bureau_loan_count", "bureau_loan_types", "bureau_days_since_last_loan",
    "bureau_days_since_first_loan", "bureau_avg_credit", "total_debt",
    "total_credit", "bureau_active_debt", "debt_to_credit_ratio",
    "bureau_max_overdue", "bureau_total_amt_overdue", "bureau_total_prolong_count",
    "bureau_global_worst_status", "bureau_total_months_overdue_across_loans",
    "bureau_global_worst_status_last_6m",
]

INS_FEATURES = [
    "ins_total_installment_tracked", "ins_worst_underpay", "ins_mean_payment_diff",
    "ins_mean_payratio", "ins_underpayment_count", "ins_worst_day_late",
    "ins_avg_day_late", "ins_late_count",
]

CC_FEATURES = [
    "cc_months_tracked", "cc_total_drawings_amt", "cc_max_single_month_drawing",
    "cc_total_drawings_count", "cc_total_atm_drawings_amt",
    "cc_atm_to_total_drawing_ratio", "cc_total_paymemt", "cc_pay_to_min_inst_ratio",
    "cc_max_balance_ever", "cc_current_balance", "cc_current_total_receivable",
    "cc_current_utilization_ratio", "cc_max_days_past_due",
    "cc_max_days_past_due_with_tolerance", "cc_month_overdue_count",
]

POS_FEATURES = [
    "pos_month_tracked", "pos_max_loan_term", "pos_current_remaining_installments",
    "pos_remaining_installment_ratio", "pos_max_days_past_due",
    "pos_max_days_past_due_with_tolerance", "pos_month_overdue_count",
]

PREV_FEATURES = [
    "prev_total_applications", "prev_days_since_last_decision", "prev_days_since_first_decision",
    "prev_total_amt_asked", "prev_total_amt_approved", "prev_credit_to_application_ratio",
    "prev_avg_annuity_amt", "prev_avg_down_payment_rate", "prev_avg_loan_term_months",
    "prev_count_refused", "prev_count_approved", "prev_count_canceled",
    "prev_rejection_rate",
] + PREV_DUMMY_FEATURES

# Application-level features from application_train/test.csv
# HAS_* flags excluded from model features — imputation artifacts only
APPLICATION_FEATURES = [
    # EXT_SOURCE
    "EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3",
    # EXT_SOURCE missingness indicators
    "MISSING_EXT_SOURCE_1", "MISSING_EXT_SOURCE_2", "MISSING_EXT_SOURCE_3",
    # Days features
    "DAYS_BIRTH", "DAYS_EMPLOYED", "DAYS_ID_PUBLISH", "DAYS_REGISTRATION", "DAYS_LAST_PHONE_CHANGE",
    # Amount features
    "AMT_INCOME_TOTAL", "AMT_CREDIT", "AMT_GOODS_PRICE", "AMT_ANNUITY",
    "AMT_REQ_CREDIT_BUREAU_HOUR", "AMT_REQ_CREDIT_BUREAU_DAY", "AMT_REQ_CREDIT_BUREAU_WEEK",
    "AMT_REQ_CREDIT_BUREAU_MON", "AMT_REQ_CREDIT_BUREAU_QRT", "AMT_REQ_CREDIT_BUREAU_YEAR",
    # Flag features
    "FLAG_OWN_CAR", "FLAG_OWN_REALTY", "FLAG_MOBIL", "FLAG_EMP_PHONE", "FLAG_WORK_PHONE",
    "FLAG_CONT_MOBILE", "FLAG_PHONE", "FLAG_EMAIL",
    "FLAG_DOCUMENT_2", "FLAG_DOCUMENT_3", "FLAG_DOCUMENT_4", "FLAG_DOCUMENT_5",
    "FLAG_DOCUMENT_6", "FLAG_DOCUMENT_7", "FLAG_DOCUMENT_8", "FLAG_DOCUMENT_9",
    "FLAG_DOCUMENT_10", "FLAG_DOCUMENT_11", "FLAG_DOCUMENT_12", "FLAG_DOCUMENT_13",
    "FLAG_DOCUMENT_14", "FLAG_DOCUMENT_15", "FLAG_DOCUMENT_16", "FLAG_DOCUMENT_17",
    "FLAG_DOCUMENT_18", "FLAG_DOCUMENT_19", "FLAG_DOCUMENT_20", "FLAG_DOCUMENT_21",
    # Categorical features
    "CODE_GENDER", "NAME_CONTRACT_TYPE", "NAME_TYPE_SUITE", "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE", "NAME_FAMILY_STATUS", "NAME_HOUSING_TYPE",
    "OCCUPATION_TYPE", "ORGANIZATION_TYPE", "WEEKDAY_APPR_PROCESS_START",
    "HOUSETYPE_MODE", "WALLSMATERIAL_MODE", "EMERGENCYSTATE_MODE", "FONDKAPREMONT_MODE",
    # Numeric application features
    "CNT_CHILDREN", "CNT_FAM_MEMBERS", "REGION_RATING_CLIENT", "REGION_RATING_CLIENT_W_CITY",
    "REGION_POPULATION_RELATIVE", "HOUR_APPR_PROCESS_START", "OWN_CAR_AGE",
    "LIVE_CITY_NOT_WORK_CITY", "REG_CITY_NOT_WORK_CITY", "REG_CITY_NOT_LIVE_CITY",
    "LIVE_REGION_NOT_WORK_REGION", "REG_REGION_NOT_LIVE_REGION", "REG_REGION_NOT_WORK_REGION",
    "OBS_30_CNT_SOCIAL_CIRCLE", "OBS_60_CNT_SOCIAL_CIRCLE",
    "DEF_30_CNT_SOCIAL_CIRCLE", "DEF_60_CNT_SOCIAL_CIRCLE",
    # Building/property numeric features
    "APARTMENTS_AVG", "APARTMENTS_MODE", "APARTMENTS_MEDI",
    "BASEMENTAREA_AVG", "BASEMENTAREA_MODE", "BASEMENTAREA_MEDI",
    "YEARS_BEGINEXPLUATATION_AVG", "YEARS_BEGINEXPLUATATION_MODE", "YEARS_BEGINEXPLUATATION_MEDI",
    "YEARS_BUILD_AVG", "YEARS_BUILD_MODE", "YEARS_BUILD_MEDI",
    "COMMONAREA_AVG", "COMMONAREA_MODE", "COMMONAREA_MEDI",
    "ELEVATORS_AVG", "ELEVATORS_MODE", "ELEVATORS_MEDI",
    "ENTRANCES_AVG", "ENTRANCES_MODE", "ENTRANCES_MEDI",
    "FLOORSMAX_AVG", "FLOORSMAX_MODE", "FLOORSMAX_MEDI",
    "FLOORSMIN_AVG", "FLOORSMIN_MODE", "FLOORSMIN_MEDI",
    "LANDAREA_AVG", "LANDAREA_MODE", "LANDAREA_MEDI",
    "LIVINGAPARTMENTS_AVG", "LIVINGAPARTMENTS_MODE", "LIVINGAPARTMENTS_MEDI",
    "LIVINGAREA_AVG", "LIVINGAREA_MODE", "LIVINGAREA_MEDI",
    "NONLIVINGAPARTMENTS_AVG", "NONLIVINGAPARTMENTS_MODE", "NONLIVINGAPARTMENTS_MEDI",
    "NONLIVINGAREA_AVG", "NONLIVINGAREA_MODE", "NONLIVINGAREA_MEDI",
    "TOTALAREA_MODE",
]

# Columns excluded from model training — presence flags used only for null-filling logic
EXCLUDE_FROM_MODEL = [
    "HAS_BUREAU_RECORD", "HAS_INSTALMENT_HISTORY", "HAS_CREDIT_CARD_HISTORY",
    "HAS_POS_HISTORY", "HAS_PREVIOUS_APPLICATION",
]

ACTIVE_FEATURES = (
    APPLICATION_FEATURES
    + BUREAU_FEATURES
    + INS_FEATURES
    + CC_FEATURES
    + POS_FEATURES
    + PREV_FEATURES
)

# ── Feature metadata ───────────────────────────────────────────────────────────
@dataclass
class FeatureMeta:
    name: str
    group: str        # "application" | "bureau" | "ins" | "cc" | "pos" | "prev"
    dtype: str        # "numeric" | "categorical" | "binary"
    fill_value: int | str
    description: str

FEATURE_REGISTRY: list[FeatureMeta] = [
    # ── Application: EXT_SOURCE ───────────────────────────────────────────────
    FeatureMeta("EXT_SOURCE_1",           "application", "numeric", -1, "Normalised score from external data source 1"),
    FeatureMeta("EXT_SOURCE_2",           "application", "numeric", -1, "Normalised score from external data source 2"),
    FeatureMeta("EXT_SOURCE_3",           "application", "numeric", -1, "Normalised score from external data source 3"),
    FeatureMeta("MISSING_EXT_SOURCE_1",   "application", "binary",   0, "1 if EXT_SOURCE_1 was missing before imputation"),
    FeatureMeta("MISSING_EXT_SOURCE_2",   "application", "binary",   0, "1 if EXT_SOURCE_2 was missing before imputation"),
    FeatureMeta("MISSING_EXT_SOURCE_3",   "application", "binary",   0, "1 if EXT_SOURCE_3 was missing before imputation"),

    # ── Application: Days ─────────────────────────────────────────────────────
    FeatureMeta("DAYS_BIRTH",             "application", "numeric", -1, "Applicant age in days relative to application (negative)"),
    FeatureMeta("DAYS_EMPLOYED",          "application", "numeric", -1, "Days employed at current job relative to application (negative)"),
    FeatureMeta("DAYS_ID_PUBLISH",        "application", "numeric", -1, "Days since ID was last changed (negative)"),
    FeatureMeta("DAYS_REGISTRATION",      "application", "numeric", -1, "Days since applicant changed registration (negative)"),
    FeatureMeta("DAYS_LAST_PHONE_CHANGE", "application", "numeric", -1, "Days since applicant last changed phone (negative)"),

    # ── Application: Amounts ──────────────────────────────────────────────────
    FeatureMeta("AMT_INCOME_TOTAL",            "application", "numeric", -1, "Applicant annual income"),
    FeatureMeta("AMT_CREDIT",                  "application", "numeric", -1, "Credit amount of the loan"),
    FeatureMeta("AMT_GOODS_PRICE",             "application", "numeric", -1, "Price of goods for which the loan is given"),
    FeatureMeta("AMT_ANNUITY",                 "application", "numeric", -1, "Loan annuity amount"),
    FeatureMeta("AMT_REQ_CREDIT_BUREAU_HOUR",  "application", "numeric",  0, "Credit bureau enquiries in last hour"),
    FeatureMeta("AMT_REQ_CREDIT_BUREAU_DAY",   "application", "numeric",  0, "Credit bureau enquiries in last day"),
    FeatureMeta("AMT_REQ_CREDIT_BUREAU_WEEK",  "application", "numeric",  0, "Credit bureau enquiries in last week"),
    FeatureMeta("AMT_REQ_CREDIT_BUREAU_MON",   "application", "numeric",  0, "Credit bureau enquiries in last month"),
    FeatureMeta("AMT_REQ_CREDIT_BUREAU_QRT",   "application", "numeric",  0, "Credit bureau enquiries in last quarter"),
    FeatureMeta("AMT_REQ_CREDIT_BUREAU_YEAR",  "application", "numeric",  0, "Credit bureau enquiries in last year"),

    # ── Application: Flag features ────────────────────────────────────────────
    FeatureMeta("FLAG_OWN_CAR",       "application", "binary", 0, "1 if applicant owns a car"),
    FeatureMeta("FLAG_OWN_REALTY",    "application", "binary", 0, "1 if applicant owns real estate"),
    FeatureMeta("FLAG_MOBIL",         "application", "binary", 0, "1 if applicant provided mobile phone"),
    FeatureMeta("FLAG_EMP_PHONE",     "application", "binary", 0, "1 if applicant provided work phone"),
    FeatureMeta("FLAG_WORK_PHONE",    "application", "binary", 0, "1 if applicant provided work phone number"),
    FeatureMeta("FLAG_CONT_MOBILE",   "application", "binary", 0, "1 if mobile phone is reachable"),
    FeatureMeta("FLAG_PHONE",         "application", "binary", 0, "1 if applicant provided home phone"),
    FeatureMeta("FLAG_EMAIL",         "application", "binary", 0, "1 if applicant provided email"),
    FeatureMeta("FLAG_DOCUMENT_2",    "application", "binary", 0, "1 if applicant provided document 2"),
    FeatureMeta("FLAG_DOCUMENT_3",    "application", "binary", 0, "1 if applicant provided document 3"),
    FeatureMeta("FLAG_DOCUMENT_4",    "application", "binary", 0, "1 if applicant provided document 4"),
    FeatureMeta("FLAG_DOCUMENT_5",    "application", "binary", 0, "1 if applicant provided document 5"),
    FeatureMeta("FLAG_DOCUMENT_6",    "application", "binary", 0, "1 if applicant provided document 6"),
    FeatureMeta("FLAG_DOCUMENT_7",    "application", "binary", 0, "1 if applicant provided document 7"),
    FeatureMeta("FLAG_DOCUMENT_8",    "application", "binary", 0, "1 if applicant provided document 8"),
    FeatureMeta("FLAG_DOCUMENT_9",    "application", "binary", 0, "1 if applicant provided document 9"),
    FeatureMeta("FLAG_DOCUMENT_10",   "application", "binary", 0, "1 if applicant provided document 10"),
    FeatureMeta("FLAG_DOCUMENT_11",   "application", "binary", 0, "1 if applicant provided document 11"),
    FeatureMeta("FLAG_DOCUMENT_12",   "application", "binary", 0, "1 if applicant provided document 12"),
    FeatureMeta("FLAG_DOCUMENT_13",   "application", "binary", 0, "1 if applicant provided document 13"),
    FeatureMeta("FLAG_DOCUMENT_14",   "application", "binary", 0, "1 if applicant provided document 14"),
    FeatureMeta("FLAG_DOCUMENT_15",   "application", "binary", 0, "1 if applicant provided document 15"),
    FeatureMeta("FLAG_DOCUMENT_16",   "application", "binary", 0, "1 if applicant provided document 16"),
    FeatureMeta("FLAG_DOCUMENT_17",   "application", "binary", 0, "1 if applicant provided document 17"),
    FeatureMeta("FLAG_DOCUMENT_18",   "application", "binary", 0, "1 if applicant provided document 18"),
    FeatureMeta("FLAG_DOCUMENT_19",   "application", "binary", 0, "1 if applicant provided document 19"),
    FeatureMeta("FLAG_DOCUMENT_20",   "application", "binary", 0, "1 if applicant provided document 20"),
    FeatureMeta("FLAG_DOCUMENT_21",   "application", "binary", 0, "1 if applicant provided document 21"),

    # ── Application: Categorical ──────────────────────────────────────────────
    FeatureMeta("CODE_GENDER",                 "application", "categorical", "Missing", "Applicant gender"),
    FeatureMeta("NAME_CONTRACT_TYPE",          "application", "categorical", "Missing", "Type of loan contract"),
    FeatureMeta("NAME_TYPE_SUITE",             "application", "categorical", "Missing", "Who accompanied applicant during application"),
    FeatureMeta("NAME_INCOME_TYPE",            "application", "categorical", "Missing", "Applicant income source type"),
    FeatureMeta("NAME_EDUCATION_TYPE",         "application", "categorical", "Missing", "Highest education level of applicant"),
    FeatureMeta("NAME_FAMILY_STATUS",          "application", "categorical", "Missing", "Applicant family status"),
    FeatureMeta("NAME_HOUSING_TYPE",           "application", "categorical", "Missing", "Applicant housing situation"),
    FeatureMeta("OCCUPATION_TYPE",             "application", "categorical", "Missing", "Applicant occupation type"),
    FeatureMeta("ORGANIZATION_TYPE",           "application", "categorical", "Missing", "Type of organisation applicant works for"),
    FeatureMeta("WEEKDAY_APPR_PROCESS_START",  "application", "categorical", "Missing", "Day of week application was started"),
    FeatureMeta("HOUSETYPE_MODE",              "application", "categorical", "Missing", "Type of house applicant lives in (mode)"),
    FeatureMeta("WALLSMATERIAL_MODE",          "application", "categorical", "Missing", "Wall material of applicant's building (mode)"),
    FeatureMeta("EMERGENCYSTATE_MODE",         "application", "categorical", "Missing", "Emergency state of applicant's building (mode)"),
    FeatureMeta("FONDKAPREMONT_MODE",          "application", "categorical", "Missing", "Type of wall material for capital repairs (mode)"),

    # ── Application: Numeric ──────────────────────────────────────────────────
    FeatureMeta("CNT_CHILDREN",                    "application", "numeric",  0, "Number of children applicant has"),
    FeatureMeta("CNT_FAM_MEMBERS",                 "application", "numeric",  0, "Number of family members"),
    FeatureMeta("REGION_RATING_CLIENT",            "application", "numeric", -1, "Home Credit rating of applicant's region"),
    FeatureMeta("REGION_RATING_CLIENT_W_CITY",     "application", "numeric", -1, "Home Credit rating of applicant's region with city"),
    FeatureMeta("REGION_POPULATION_RELATIVE",      "application", "numeric", -1, "Normalised population of applicant's region"),
    FeatureMeta("HOUR_APPR_PROCESS_START",         "application", "numeric", -1, "Hour of day application process started"),
    FeatureMeta("OWN_CAR_AGE",                     "application", "numeric",  0, "Age of applicant's car in years (0 if no car)"),
    FeatureMeta("LIVE_CITY_NOT_WORK_CITY",         "application", "numeric",  0, "1 if applicant lives in different city than works"),
    FeatureMeta("REG_CITY_NOT_WORK_CITY",          "application", "numeric",  0, "1 if registered city differs from work city"),
    FeatureMeta("REG_CITY_NOT_LIVE_CITY",          "application", "numeric",  0, "1 if registered city differs from living city"),
    FeatureMeta("LIVE_REGION_NOT_WORK_REGION",     "application", "numeric",  0, "1 if living region differs from work region"),
    FeatureMeta("REG_REGION_NOT_LIVE_REGION",      "application", "numeric",  0, "1 if registered region differs from living region"),
    FeatureMeta("REG_REGION_NOT_WORK_REGION",      "application", "numeric",  0, "1 if registered region differs from work region"),
    FeatureMeta("OBS_30_CNT_SOCIAL_CIRCLE",        "application", "numeric",  0, "Observations of social circle defaulting in 30 days"),
    FeatureMeta("OBS_60_CNT_SOCIAL_CIRCLE",        "application", "numeric",  0, "Observations of social circle defaulting in 60 days"),
    FeatureMeta("DEF_30_CNT_SOCIAL_CIRCLE",        "application", "numeric",  0, "Defaults in social circle within 30 days"),
    FeatureMeta("DEF_60_CNT_SOCIAL_CIRCLE",        "application", "numeric",  0, "Defaults in social circle within 60 days"),

    # ── Application: Building/property ───────────────────────────────────────
    FeatureMeta("APARTMENTS_AVG",              "application", "numeric", -1, "Normalised apartment size (avg)"),
    FeatureMeta("APARTMENTS_MODE",             "application", "numeric", -1, "Normalised apartment size (mode)"),
    FeatureMeta("APARTMENTS_MEDI",             "application", "numeric", -1, "Normalised apartment size (median)"),
    FeatureMeta("BASEMENTAREA_AVG",            "application", "numeric", -1, "Normalised basement area (avg)"),
    FeatureMeta("BASEMENTAREA_MODE",           "application", "numeric", -1, "Normalised basement area (mode)"),
    FeatureMeta("BASEMENTAREA_MEDI",           "application", "numeric", -1, "Normalised basement area (median)"),
    FeatureMeta("YEARS_BEGINEXPLUATATION_AVG", "application", "numeric", -1, "Normalised year building started operation (avg)"),
    FeatureMeta("YEARS_BEGINEXPLUATATION_MODE","application", "numeric", -1, "Normalised year building started operation (mode)"),
    FeatureMeta("YEARS_BEGINEXPLUATATION_MEDI","application", "numeric", -1, "Normalised year building started operation (median)"),
    FeatureMeta("YEARS_BUILD_AVG",             "application", "numeric", -1, "Normalised year building was built (avg)"),
    FeatureMeta("YEARS_BUILD_MODE",            "application", "numeric", -1, "Normalised year building was built (mode)"),
    FeatureMeta("YEARS_BUILD_MEDI",            "application", "numeric", -1, "Normalised year building was built (median)"),
    FeatureMeta("COMMONAREA_AVG",              "application", "numeric", -1, "Normalised common area size (avg)"),
    FeatureMeta("COMMONAREA_MODE",             "application", "numeric", -1, "Normalised common area size (mode)"),
    FeatureMeta("COMMONAREA_MEDI",             "application", "numeric", -1, "Normalised common area size (median)"),
    FeatureMeta("ELEVATORS_AVG",               "application", "numeric", -1, "Normalised number of elevators (avg)"),
    FeatureMeta("ELEVATORS_MODE",              "application", "numeric", -1, "Normalised number of elevators (mode)"),
    FeatureMeta("ELEVATORS_MEDI",              "application", "numeric", -1, "Normalised number of elevators (median)"),
    FeatureMeta("ENTRANCES_AVG",               "application", "numeric", -1, "Normalised number of entrances (avg)"),
    FeatureMeta("ENTRANCES_MODE",              "application", "numeric", -1, "Normalised number of entrances (mode)"),
    FeatureMeta("ENTRANCES_MEDI",              "application", "numeric", -1, "Normalised number of entrances (median)"),
    FeatureMeta("FLOORSMAX_AVG",               "application", "numeric", -1, "Normalised maximum floors in building (avg)"),
    FeatureMeta("FLOORSMAX_MODE",              "application", "numeric", -1, "Normalised maximum floors in building (mode)"),
    FeatureMeta("FLOORSMAX_MEDI",              "application", "numeric", -1, "Normalised maximum floors in building (median)"),
    FeatureMeta("FLOORSMIN_AVG",               "application", "numeric", -1, "Normalised minimum floors in building (avg)"),
    FeatureMeta("FLOORSMIN_MODE",              "application", "numeric", -1, "Normalised minimum floors in building (mode)"),
    FeatureMeta("FLOORSMIN_MEDI",              "application", "numeric", -1, "Normalised minimum floors in building (median)"),
    FeatureMeta("LANDAREA_AVG",                "application", "numeric", -1, "Normalised land area (avg)"),
    FeatureMeta("LANDAREA_MODE",               "application", "numeric", -1, "Normalised land area (mode)"),
    FeatureMeta("LANDAREA_MEDI",               "application", "numeric", -1, "Normalised land area (median)"),
    FeatureMeta("LIVINGAPARTMENTS_AVG",        "application", "numeric", -1, "Normalised living apartment size (avg)"),
    FeatureMeta("LIVINGAPARTMENTS_MODE",       "application", "numeric", -1, "Normalised living apartment size (mode)"),
    FeatureMeta("LIVINGAPARTMENTS_MEDI",       "application", "numeric", -1, "Normalised living apartment size (median)"),
    FeatureMeta("LIVINGAREA_AVG",              "application", "numeric", -1, "Normalised living area size (avg)"),
    FeatureMeta("LIVINGAREA_MODE",             "application", "numeric", -1, "Normalised living area size (mode)"),
    FeatureMeta("LIVINGAREA_MEDI",             "application", "numeric", -1, "Normalised living area size (median)"),
    FeatureMeta("NONLIVINGAPARTMENTS_AVG",     "application", "numeric", -1, "Normalised non-living apartment size (avg)"),
    FeatureMeta("NONLIVINGAPARTMENTS_MODE",    "application", "numeric", -1, "Normalised non-living apartment size (mode)"),
    FeatureMeta("NONLIVINGAPARTMENTS_MEDI",    "application", "numeric", -1, "Normalised non-living apartment size (median)"),
    FeatureMeta("NONLIVINGAREA_AVG",           "application", "numeric", -1, "Normalised non-living area size (avg)"),
    FeatureMeta("NONLIVINGAREA_MODE",          "application", "numeric", -1, "Normalised non-living area size (mode)"),
    FeatureMeta("NONLIVINGAREA_MEDI",          "application", "numeric", -1, "Normalised non-living area size (median)"),
    FeatureMeta("TOTALAREA_MODE",              "application", "numeric", -1, "Normalised total area of building (mode)"),

    # ── Bureau ────────────────────────────────────────────────────────────────
    FeatureMeta("bureau_loan_count",                        "bureau", "numeric",  0, "Total number of external bureau loans"),
    FeatureMeta("bureau_loan_types",                        "bureau", "numeric",  0, "Number of distinct credit types in bureau"),
    FeatureMeta("bureau_days_since_last_loan",              "bureau", "numeric",  0, "Days since most recent bureau loan opened"),
    FeatureMeta("bureau_days_since_first_loan",             "bureau", "numeric",  0, "Days since oldest bureau loan opened"),
    FeatureMeta("bureau_avg_credit",                        "bureau", "numeric", -1, "Mean credit amount across all bureau loans"),
    FeatureMeta("total_debt",                               "bureau", "numeric",  0, "Sum of outstanding debt across all bureau loans"),
    FeatureMeta("total_credit",                             "bureau", "numeric",  0, "Sum of total credit amount across all bureau loans"),
    FeatureMeta("bureau_active_debt",                       "bureau", "numeric",  0, "Outstanding debt on currently active bureau loans"),
    FeatureMeta("debt_to_credit_ratio",                     "bureau", "numeric", -1, "Total debt divided by total credit"),
    FeatureMeta("bureau_max_overdue",                       "bureau", "numeric",  0, "Maximum days overdue ever recorded in bureau"),
    FeatureMeta("bureau_total_amt_overdue",                 "bureau", "numeric",  0, "Total overdue amount summed across bureau loans"),
    FeatureMeta("bureau_total_prolong_count",               "bureau", "numeric",  0, "Total number of times bureau loans were prolonged"),
    FeatureMeta("bureau_global_worst_status",               "bureau", "numeric",  0, "Worst monthly DPD status ever across bureau loans"),
    FeatureMeta("bureau_total_months_overdue_across_loans", "bureau", "numeric",  0, "Total overdue months summed across bureau loans"),
    FeatureMeta("bureau_global_worst_status_last_6m",       "bureau", "numeric",  0, "Worst DPD status across bureau loans in last 6 months"),

    # ── Installments ──────────────────────────────────────────────────────────
    FeatureMeta("ins_total_installment_tracked", "ins", "numeric",  0, "Total number of installment records tracked"),
    FeatureMeta("ins_worst_underpay",            "ins", "numeric", -1, "Largest single underpayment (most negative pay diff)"),
    FeatureMeta("ins_mean_payment_diff",         "ins", "numeric", -1, "Mean difference between amount paid and amount due"),
    FeatureMeta("ins_mean_payratio",             "ins", "numeric", -1, "Mean ratio of payment made to installment due"),
    FeatureMeta("ins_underpayment_count",        "ins", "numeric",  0, "Number of installments where payment was less than due"),
    FeatureMeta("ins_worst_day_late",            "ins", "numeric", -1, "Maximum days late across all installment payments"),
    FeatureMeta("ins_avg_day_late",              "ins", "numeric", -1, "Average days late across all installment payments"),
    FeatureMeta("ins_late_count",                "ins", "numeric",  0, "Number of installments paid late"),

    # ── Credit Card ───────────────────────────────────────────────────────────
    FeatureMeta("cc_months_tracked",                   "cc", "numeric",  0, "Total months of credit card history tracked"),
    FeatureMeta("cc_total_drawings_amt",               "cc", "numeric",  0, "Total amount drawn on credit card across all months"),
    FeatureMeta("cc_max_single_month_drawing",         "cc", "numeric",  0, "Largest drawing amount in a single month"),
    FeatureMeta("cc_total_drawings_count",             "cc", "numeric",  0, "Total number of credit card drawings"),
    FeatureMeta("cc_total_atm_drawings_amt",           "cc", "numeric",  0, "Total ATM drawing amount across all months"),
    FeatureMeta("cc_atm_to_total_drawing_ratio",       "cc", "numeric", -1, "ATM drawings as a share of total drawings"),
    FeatureMeta("cc_total_paymemt",                    "cc", "numeric",  0, "Total payments made on credit card across all months"),
    FeatureMeta("cc_pay_to_min_inst_ratio",            "cc", "numeric", -1, "Total payments relative to total minimum installments due"),
    FeatureMeta("cc_max_balance_ever",                 "cc", "numeric",  0, "Highest credit card balance ever recorded"),
    FeatureMeta("cc_current_balance",                  "cc", "numeric",  0, "Credit card balance in the most recent month"),
    FeatureMeta("cc_current_total_receivable",         "cc", "numeric",  0, "Total receivable amount in the most recent month"),
    FeatureMeta("cc_current_utilization_ratio",        "cc", "numeric", -1, "Current balance divided by current credit limit"),
    FeatureMeta("cc_max_days_past_due",                "cc", "numeric",  0, "Maximum days past due ever on credit card"),
    FeatureMeta("cc_max_days_past_due_with_tolerance", "cc", "numeric",  0, "Maximum DPD with tolerance ever on credit card"),
    FeatureMeta("cc_month_overdue_count",              "cc", "numeric",  0, "Number of months with any credit card overdue"),

    # ── POS Cash ──────────────────────────────────────────────────────────────
    FeatureMeta("pos_month_tracked",                    "pos", "numeric",  0, "Total months of POS cash history tracked"),
    FeatureMeta("pos_max_loan_term",                    "pos", "numeric",  0, "Maximum loan term seen in POS"),
    FeatureMeta("pos_current_remaining_installments",   "pos", "numeric",  0, "Remaining installments on most recent POS loan"),
    FeatureMeta("pos_remaining_installment_ratio",      "pos", "numeric", -1, "Remaining installments as share of total loan term"),
    FeatureMeta("pos_max_days_past_due",                "pos", "numeric",  0, "Maximum days past due ever on POS loans"),
    FeatureMeta("pos_max_days_past_due_with_tolerance", "pos", "numeric",  0, "Maximum DPD with tolerance ever on POS loans"),
    FeatureMeta("pos_month_overdue_count",              "pos", "numeric",  0, "Number of months with any POS overdue"),

    # ── Previous Applications ─────────────────────────────────────────────────
    FeatureMeta("prev_total_applications",              "prev", "numeric",  0,  "Total number of previous loan applications"),
    FeatureMeta("prev_days_since_last_decision",        "prev", "numeric",  0,  "Days since most recent application decision"),
    FeatureMeta("prev_days_since_first_decision",       "prev", "numeric",  0,  "Days since first ever application decision"),
    FeatureMeta("prev_total_amt_asked",                 "prev", "numeric",  0,  "Total loan amount requested across previous applications"),
    FeatureMeta("prev_total_amt_approved",              "prev", "numeric",  0,  "Total loan amount approved across previous applications"),
    FeatureMeta("prev_credit_to_application_ratio",     "prev", "numeric", -1,  "Approved amount relative to requested amount"),
    FeatureMeta("prev_avg_annuity_amt",                 "prev", "numeric", -1,  "Mean annuity amount across previous applications"),
    FeatureMeta("prev_avg_down_payment_rate",           "prev", "numeric", -1,  "Mean down payment rate across previous applications"),
    FeatureMeta("prev_avg_loan_term_months",            "prev", "numeric", -1,  "Mean loan term in months across previous applications"),
    FeatureMeta("prev_count_refused",                   "prev", "numeric",  0,  "Number of previous applications refused"),
    FeatureMeta("prev_count_approved",                  "prev", "numeric",  0,  "Number of previous applications approved"),
    FeatureMeta("prev_count_canceled",                  "prev", "numeric",  0,  "Number of previous applications canceled"),
    FeatureMeta("prev_rejection_rate",                  "prev", "numeric", -1,  "Share of previous applications that were refused"),
    FeatureMeta("prev_most_recent_status_Approved",     "prev", "binary",   0,  "Most recent application was Approved"),
    FeatureMeta("prev_most_recent_status_Refused",      "prev", "binary",   0,  "Most recent application was Refused"),
    FeatureMeta("prev_most_recent_status_Canceled",     "prev", "binary",   0,  "Most recent application was Canceled"),
    FeatureMeta("prev_most_recent_status_Unused offer", "prev", "binary",   0,  "Most recent application was an Unused offer"),
]

# ── Registry helpers ───────────────────────────────────────────────────────────
_REGISTRY_MAP: dict[str, FeatureMeta] = {f.name: f for f in FEATURE_REGISTRY}

def get_feature_cols(exclude_groups: list[str] | None = None) -> list[str]:
    """Return all model-ready feature column names, optionally excluding groups."""
    exclude_groups = set(exclude_groups or [])
    return [f.name for f in FEATURE_REGISTRY if f.group not in exclude_groups]

def get_group_cols(group: str) -> list[str]:
    """Return all feature names belonging to a specific group."""
    return [f.name for f in FEATURE_REGISTRY if f.group == group]

def get_numeric_cols(exclude_groups: list[str] | None = None) -> list[str]:
    exclude_groups = set(exclude_groups or [])
    return [f.name for f in FEATURE_REGISTRY if f.dtype == "numeric" and f.group not in exclude_groups]

def get_categorical_cols(exclude_groups: list[str] | None = None) -> list[str]:
    exclude_groups = set(exclude_groups or [])
    return [f.name for f in FEATURE_REGISTRY if f.dtype == "categorical" and f.group not in exclude_groups]

def get_binary_cols(exclude_groups: list[str] | None = None) -> list[str]:
    exclude_groups = set(exclude_groups or [])
    return [f.name for f in FEATURE_REGISTRY if f.dtype == "binary" and f.group not in exclude_groups]

def get_fill_map(exclude_groups: list[str] | None = None) -> dict[str, int | str]:
    """Return {col: fill_value} for all features — useful for re-imputation at inference time."""
    exclude_groups = set(exclude_groups or [])
    return {f.name: f.fill_value for f in FEATURE_REGISTRY if f.group not in exclude_groups}

def validate_registry_against_df(df: pl.DataFrame) -> None:
    """
    Sanity check: raises if any registered feature is missing from the dataframe,
    or if the dataframe has unexpected nulls after filling.
    """
    missing_cols = [f.name for f in FEATURE_REGISTRY if f.name not in df.columns]
    if missing_cols:
        raise ValueError(f"Registry features missing from dataframe: {missing_cols}")

    unexpected_nulls = [f.name for f in FEATURE_REGISTRY if df[f.name].null_count() > 0]
    if unexpected_nulls:
        raise ValueError(f"Unexpected nulls after filling: {unexpected_nulls}")

    print(f"Registry validation passed — {len(FEATURE_REGISTRY)} features checked.")